Nihon + Silent Hills Groundwork
Currently doesn't build due to a weird error

```
rgbasm -hL -Q8 -P includes.asm -Weverything -Wnumeric-string=2 -Wtruncation=1  -o data/maps/map_data.o data/maps/map_data.asm
error: data/maps/map_data.asm(3) -> data/maps/maps.asm(544) -> macros/asserts.as
m::assert_table_length(14):
    Expected constant expression: 'NUM_SILENT_HILLS_MAP' is not constant at asse
mbly time
error: data/maps/map_data.asm(3) -> data/maps/maps.asm(544) -> macros/asserts.as
m::assert_table_length(16):
    Assertion failed: MapGroup_SilentHills: expected 0 entries, each 9 bytes
error: Assembly aborted (2 errors)!
make: *** [Makefile:119: data/maps/map_data.o] Error 1
```